### ISSUE TITLE
Change library to typescript and react hooks

### ISSUE THREAD

**Issue by banarualexandru** [gomjellie/react-native-timetable#17]
Hello
Small and nice library!

Do you have plans to use react hooks in the near future? Because now it gives a warning for  classic lifetime methods like ComponentDidMount

Thanks

**Comment by gomjellie** [comment]
I don't wanna change whole library into typescript but I think it's good to support typescript using .d.ts. files

**Comment by gomjellie** [comment]
and yeah it's needed to update life cycle methods but recently I'm just too busy to do that.

**Comment by guy490** [comment]
> and yeah it's needed to update life cycle methods but recently I'm just too busy to do that.

I will be happy contribute to this tool with change it to React Hooks

**Comment by rubycho** [comment]
Anyone interested on this issue?
I tried to use dts-gen to create .d.ts files, but it doesn't work. (seems the generator doesn't understands ES6, such as import statement).

**Comment by guy490** [comment]
> Anyone interested on this issue?
> I tried to use dts-gen to create .d.ts files, but it doesn't work.
> (seems the generator doesn't understands ES6, such as import statement).

I'm interested to work on replacing all to React Hooks.
Can start work on it tomorrow.

**Comment by rubycho** [comment]
> > Anyone interested on this issue?
> > I tried to use dts-gen to create .d.ts files, but it doesn't work.
> > (seems the generator doesn't understands ES6, such as import statement).
> 
> I'm interested to work on replacing all to React Hooks.
> Can start work on it tomorrow.

Thanks for your reply.
Well, I'm not a skilled react-native developer, so could you elaborate about replacing all to React Hooks? or specific plans.
Does it mean replacing Class components to Functional components and converting the states or initial codes to hooks like useState and useEffect?

**Comment by guy490** [comment]
> > > Anyone interested on this issue?
> > > I tried to use dts-gen to create .d.ts files, but it doesn't work.
> > > (seems the generator doesn't understands ES6, such as import statement).
> > 
> > 
> > I'm interested to work on replacing all to React Hooks.
> > Can start work on it tomorrow.
> 
> Thanks for your reply.
> Well, I'm not a skilled react-native developer, so could you elaborate about replacing all to React Hooks? or specific plans.
> Does it mean replacing Class components to Functional components and converting the states or initial codes to hooks like useState and useEffect?

Yes, Exactly.

**Comment by rubycho** [comment]
So the class components in this library are `TimeTableView.js` and `Event.js`. Could you convert that both?

**Comment by guy490** [comment]
> So the class components in this library are `TimeTableView.js` and `Event.js`. Could you convert that both?

Yes

**Comment by rubycho** [comment]
Thanks. I'll wait for the pr.

**Comment by guy490** [comment]
@gomjellie @rubycho 
Hey, I have been upgraded it to react hooks, and it seems ok.
but still didnt checked it and see that there is no bugs.

But i have a problem with runnig the example project ... I got an error:

`Module not found: Can't resolve 'react-native' in 'C:\Users\Guy\Desktop\New folder\react-native-timetable\example'`

I have installed all the packages but it still not recognizing it, what i'm missing with running it?

**Comment by rubycho** [comment]
Does the error occurs on `yarn start`?
Have you run `yarn install` on the `example` directory?

**Comment by guy490** [comment]
> Does the error occurs on `yarn start`?
> Have you run `yarn install` on the `example` directory?

I have installed with `npm install`, it has difference from the yarn install?

**Comment by rubycho** [comment]
@guy490 
Both are package managers, and by project convention we are using yarn.
But npm should work too.

If the problem persists, you could just create temporary react native app project, copy codes from example and test it.

**Comment by Nahoyhp** [comment]
Hi, I am trying to set up before I try to contribute (I am a first timer to OSS contribution). But I encounter the same problem as @guy490 . Can you share your solution on solving this problem?

**Comment by rubycho** [comment]
Hi, @Nahoyhp 
Currently `yarn link` or `npm link` seems to fail on react-native projects, cause the packager doesn't support [symlinks](https://stackoverflow.com/questions/44061155/react-native-npm-link-local-dependency-unable-to-resolve-module).
Running `yarn add <path_to_repo>/src` can be a solution to install package from local source. Though you will need to re-install after having changes on package source files. (and this method is really annoying for cross-developing)
