### ISSUE TITLE
Timetable body not showing

### ISSUE THREAD

**Issue by majid-achy** [gomjellie/react-native-timetable#21]
Hello,
First your library is very good it helped me a lot but i am having an issue. I used your library for a project and it was working. Then i updated my navigation library from react-navigation v3 to v5 and the body of the timetable stopped showing i think that the issue may be from the upgrade of react navigation. I tried it on a fresh project with only dependencies the ones for react navigation 5 still did not work (the data i used is the data provided by your example) the dependencies of the project are: 
"dependencies": {
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/bottom-tabs": "^5.0.0",
    "@react-navigation/drawer": "^5.0.0",
    "@react-navigation/native": "^5.0.0",
    "@react-navigation/stack": "^5.0.0",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-gesture-handler": "^1.5.6",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.7.2",
    "react-native-screens": "^2.0.0-beta.2",
    "react-native-timetable": "^1.0.4",
    "react-native-vector-icons": "^6.6.0"
  }
This is the file containing the code:
[Home.zip](https://github.com/gomjellie/react-native-timetable/files/4384382/Home.zip)
Sorry if there is something missing in this report it is my first time doing it.
Thanks in advance for you time.

**Comment by gomjellie** [comment]
are you still in trouble with this?

sorry but I can't simulate your problem. need more source codes, can i get more codes?

**Comment by majid-achy** [comment]
I uploaded the project to github here is the link https://github.com/majid-achy/project-timetable

**Comment by majid-achy** [comment]
Did you check the repo I shared? Yesterday I tried to see what part of the code was causing the body not to show but I did not find any result

**Comment by gomjellie** [comment]
@majid-achy 
I'm sorry for being late. I've been so busy doing homework.
can I check it when I'm free? to be honest, I'm not sure when it is. so sorry again

**Comment by majid-achy** [comment]
No problem but don't forget me and good luck with your homeworks.

**Comment by gomjellie** [comment]
what about to use [teaset](https://github.com/rilyu/teaset) instead of react-navigation? I didn't find any problem with teaset.

**Comment by majid-achy** [comment]
The problem is I am using it in a bigger project that already uses react-navigation and switching to another library now is very time consuming so I want to know what is the problem that does not let the timetable body to show

**Comment by majid-achy** [comment]
Ok solved it. Thank you for your time.

**Comment by astonedf** [comment]
@majid-achy hi, I’m having the same issue as you, how did you solve it?
