### ISSUE TITLE
how to pass value to events_data from API fetch 

### ISSUE THREAD

**Issue by mubarak989** [gomjellie/react-native-timetable#32]
i have function that fetch data same as `events_data `
i want to pass the values returned from this function to the object `events_data `
```
function getvals() {

    return fetch('http://***********/users/timetable')
        .then(response => response.json())
        .then((responseData) => {
            console.log(responseData);
            return responseData;
        })

        .catch(error => console.log(error))
}
```
so here responseData it returned something like this:
`  [{"day": "FRI", "end_time": 11, "start_time": 9}, {"day": "MON", "end_time": 1, "start_time": 11}, {"day": "WED", "end_time": 3, "start_time": 2}, {"day": "TUE", "end_time": 12, "start_time": 10}] `

for example I want to set the value of day name in `events_data ` to the value of day coming from `getvals()` function

**Comment by gomjellie** [comment]
use state variable
put setState({events_data: `your_response_data`}) in your getvals function and pass it to TimeTableView

**Comment by rubycho** [comment]
As @gomjellie mentioned, you can handle it by calling `setState` in callback (or promise, or async).
Or `set{yourState}(responseData);` and feeding `yourState` to the `TimeTableView` component, if you're using hooks.

**Comment by mubarak989** [comment]
@gomjellie @rubycho thank for replying, after hours of headache o have managed to do that using the following code (i used setState to do that as you guys mentioned )
 ```
const [data, setData] = useState([]);
    useEffect(() => {
        fetch('http://192.168.0.106:3000/users/timetable')
            .then((response) => response.json()) 
            .then(function (output) {
                output.forEach((d) => {
                    output.push({
                        title: d.name,
                        startTime: genTimeBlock(d.day, d.start_time),
                        endTime: genTimeBlock(d.day, d.end_time),
                        location: d.location,
                    });
                });
                setData(output)
                //console.log(output)
            })
            .catch((error) => console.error(error))
    }, []);
```
then in event prop i called the state data[]:   `events={data}`
