### ISSUE TITLE
Pass events data or signle value of the event array data on press function

### ISSUE THREAD

**Issue by mubarak989** [gomjellie/react-native-timetable#33]
Hi, 
as known that the events are all array and then showing in the timetable view based on time and day, so if one of these events pressed, the `onEventPress` function will pass its value to the function. 
what I did is as follow:
```
<TimeTableView
                                        //scrollViewRef={scrollViewRef}
                                        events={data}
                                        pivotTime={8}
                                        pivotDate={pivotDate}
                                        numberOfDays={numOfDays}
                                        onEventPress={() => onEventPress(data)}
                                        headerStyle={styles.headerStyle}
                                        formatDateHeader="dddd"
                                        locale="en"
                                    />
```
so I passed the events data through` onEventPress(data)`  however, when I console.log(data) in the  `onEventPress()` after it has been passed, it pass all the data of the array of all events in the timetable view not only the pressed event data.
**but I want only the pressed event data to be passed.**
i hope that is clear and someone can help me to solve this issue.

**Comment by rubycho** [comment]
Hi @mubarak989 ,
The signature of `onEventPress` is `function (e) { ... }`, where e is the event object which is pressed.
Your code seems to just passing the original data array to your callback.

**Comment by mubarak989** [comment]
thanks @rubycho for replying 
oh yes this great I did mistake by passing the all array.  another simple question, is it possible to add one more data to the array
for example:  
if i want to add to the array also after `extra_ description` another title for example named `id ` i think is possible but i alter and do changes in the original code?
